# Introduction to the JupyterLab and Jupyter Notebooks

This is a short introduction to two of the flagship tools created by [the Jupyter Community](https://jupyter.org).

> **⚠️Experimental!⚠️**: This is an experimental interface provided by the [JupyterLite project](https://jupyterlite.readthedocs.io/en/latest/). It embeds an entire JupyterLab interface, with many popular packages for scientific computing, in your browser. There may be minor differences in behavior between JupyterLite and the JupyterLab you install locally. You may also encounter some bugs or unexpected behavior. To report any issues, or to get involved with the JupyterLite project, see [the JupyterLite repository](https://github.com/jupyterlite/jupyterlite/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

## JupyterLab 🧪

**JupyterLab** is a next-generation web-based user interface for Project Jupyter. It enables you to work with documents and activities such as Jupyter notebooks, text editors, terminals, and custom components in a flexible, integrated, and extensible manner. It is the interface that you're looking at right now.

**For an overview of the JupyterLab interface**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Welcome Tour` and following the prompts.

> **See Also**: For a more in-depth tour of JupyterLab with a full environment that runs in the cloud, see [the JupyterLab introduction on Binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/HEAD?urlpath=lab/tree/demo).

## Jupyter Notebooks 📓

**Jupyter Notebooks** are a community standard for communicating and performing interactive computing. They are a document that blends computations, outputs, explanatory text, mathematics, images, and rich media representations of objects.

JupyterLab is one interface used to create and interact with Jupyter Notebooks.

**For an overview of Jupyter Notebooks**, see the **JupyterLab Welcome Tour** on this page, by going to `Help -> Notebook Tour` and following the prompts.

> **See Also**: For a more in-depth tour of Jupyter Notebooks and the Classic Jupyter Notebook interface, see [the Jupyter Notebook IPython tutorial on Binder](https://mybinder.org/v2/gh/ipython/ipython-in-depth/HEAD?urlpath=tree/binder/Index.ipynb).

## An example: visualizing data in the notebook ✨

Below is an example of a code cell. We'll visualize some simple data using two popular packages in Python. We'll use [NumPy](https://numpy.org/) to create some random data, and [Matplotlib](https://matplotlib.org) to visualize it.

Note how the code and the results of running the code are bundled together.

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
n=arr.ndim
print(n)

2


In [4]:
arrr=np.fromstring('22 23 24',dtype=int,sep=" ")

In [16]:
print(arrr)

[22 23 24]


In [5]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [6]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [1]:
import numpy as np

In [9]:
import numpy as np

# Generate a 5x6 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(5, 6))

print(arr)


[[41 15  6 63 46 89]
 [63 39 20  1 60 35]
 [73 67 55 32 91 10]
 [ 7  8 91 92  4 43]
 [65 96 69 87 90 96]]


In [10]:
print(arr.T)

[[41 63 73  7 65]
 [15 39 67  8 96]
 [ 6 20 55 91 69]
 [63  1 32 92 87]
 [46 60 91  4 90]
 [89 35 10 43 96]]


In [12]:
arr1=np.random.randint(1,10,10)

In [13]:
arr1

array([7, 6, 1, 4, 5, 9, 6, 8, 4, 3])

In [14]:
arr1.reshape(2,5)

array([[7, 6, 1, 4, 5],
       [9, 6, 8, 4, 3]])

In [15]:
arr1.reshape(5,2)

array([[7, 6],
       [1, 4],
       [5, 9],
       [6, 8],
       [4, 3]])

In [19]:
arr2 = np.random.rand(4, 4)

In [20]:
new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(new_arr)

[[ 0  0  0  0  0  0  0  0]
 [ 0 41 15  6 63 46 89  0]
 [ 0 63 39 20  1 60 35  0]
 [ 0 73 67 55 32 91 10  0]
 [ 0  7  8 91 92  4 43  0]
 [ 0 65 96 69 87 90 96  0]
 [ 0  0  0  0  0  0  0  0]]


In [21]:
arr3=np.linespace(10,50,5)

<class 'AttributeError'>: module 'numpy' has no attribute 'linespace'

In [22]:
arr4=np.arange(10, 65, 5)

In [23]:
print(arr4)

[10 15 20 25 30 35 40 45 50 55 60]


In [25]:
arr5=np.array(['python','numpy','pandas'])
print(arr5)

['python' 'numpy' 'pandas']


In [26]:
print(np.char.upper(arr5))

['PYTHON' 'NUMPY' 'PANDAS']


In [27]:
print(np.char.lower(arr5))

['python' 'numpy' 'pandas']


In [28]:
print(np.char.capitalize(arr5))

['Python' 'Numpy' 'Pandas']


In [29]:
arr6 = np.array(['python', 'numpy', 'pandas'])
spaced_arr = np.char.join(' ', arr6)

In [30]:
print(spaced_arr)

['p y t h o n' 'n u m p y' 'p a n d a s']


In [31]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Step 2: Perform element-wise operations

# Element-wise addition
addition = arr1 + arr2

# Element-wise subtraction
subtraction = arr1 - arr2

# Element-wise multiplication
multiplication = arr1 * arr2

# Element-wise division
division = arr1 / arr2

# Step 3: Print the results
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[6 5 4]
 [3 2 1]]

Element-wise Addition:
 [[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
 [[ 6 10 12]
 [12 10  6]]

Element-wise Division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [32]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Step 3: Print the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]


In [33]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):  # Check divisibility up to sqrt(num)
        if num % i == 0:
            return False
    return True

# Step 3: Find prime numbers using a for loop
prime_numbers = []
for num in arr:
    if is_prime(num):
        prime_numbers.append(num)

# Convert the result back to a NumPy array
prime_numbers = np.array(prime_numbers)

# Step 4: Print the original array and the prime numbers found
print("Original Array:\n", arr)
print("\nPrime Numbers in the Array:\n", prime_numbers)


Original Array:
 [598 167 932 197 544  84  27 214 818 399 867 291 619 470 245 458 777 236
 823 134 465 198 655  25  89 893 375   4 552 943 306 262 225 405 404 282
 357 350 308 380  86 821 520 913 330 957 727 914 313 733 491 309 592 867
 868 216  34 426  99 666 346  68 383 403  39 678 606 119 226  54 448 158
 185 907 689 951  64 732 725 177 723 688 778 758 750 299 866 261 557 820
 515 532 964 751 230 385 860 738 805 716]

Prime Numbers in the Array:
 [167 197 619 823  89 821 727 313 733 491 383 907 557 751]


In [34]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 35, size=30)  # Random temperatures between 20 and 35 degrees Celsius

# Step 2: Reshape the array to 4 weeks (7 days per week)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Step 4: Print the daily temperatures and weekly averages
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:\n", weekly_averages)


<class 'ValueError'>: cannot reshape array of size 30 into shape (4,7)